/******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the Ultrasonic driver
 *
 * Author: carlos wagdy
 *
 *******************************************************************************/

#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include <util/delay.h>

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

uint16 g_timePulse = 0;
uint8  g_edgeCount = 0;

ICU_ConfigType ICU_config = {
		F_CPU_8,
		RAISING
};

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description :
 * Initialize the ICU driver as required:
 * 1. Set up the ICU callback function.
 * 2. Set the direction for the trigger pin as output through
      the GPIO driver
 */
void Ultrasonic_init(void)
{
	ICU_init(&ICU_config);
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, PIN_OUTPUT);
}

/*
 * Description:
 * Send the trigger pulse to the ultrasonic sensor
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_HIGH);
	_delay_us(20);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_LOW);
}

/*
 * Description:
 * Send the trigger pulse by using the Ultrasonic_Trigger
   function.
 *  Start the measurement process via the ICU driver
 */
uint16 Ultrasonic_readDistance(void)
{
	Ultrasonic_Trigger();

	uint16 distance = (uint16)(g_timePulse / 117.6);

	return distance;
}

/*
 * Description:
 * This is the callback function called by the ICU driver.
 *  It calculates the high time (pulse time) generated by
    the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;

	switch(g_edgeCount)
	{
	case 1:
		ICU_clearTimerValue();
		ICU_setEdgeDetectionType(FALLING);
		break;
	case 2:
		g_timePulse = ICU_getInputCaptureValue();
		ICU_clearTimerValue();
		ICU_setEdgeDetectionType(RAISING);
		g_edgeCount = 0;
		break;
	}
}
